version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: adharaprojects/basic-docker-base:0.0.0
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Create virtual network for test
          command: |
            docker network create cyclos-cbs-proxy-test

      - run:
          name: Start CyclosDB
          command: |
            docker run --name cyclos-db --network=cyclos-cbs-proxy-test \
              -e POSTGRES_DB=cyclos \
              -e POSTGRES_USER=cyclos \
              -e POSTGRES_PASSWORD=cyclospwd \
              -d adharaprojects/cyclos:basic_0

      - run:
          name: Start Cyclos
          command: |
            docker run --name cyclos --network=cyclos-cbs-proxy-test \
              -e DB_HOST=cyclos-db \
              -e DB_NAME=cyclos \
              -e DB_USER=cyclos \
              -e DB_PASSWORD=cyclospwd \
              -p "4001:8080" \
              -d cyclos/cyclos

      - run:
          name: Build the CBS-proxy docker image and run the test
          command: |
            docker build -t adharaprojects/cbs-proxy:temp-ci-test .
            # TODO: use the `cyclos-cbs-proxy-test` network and use port 8080 instead then (do this when you have a proper config file)
            docker run --name cbs-proxy \
              --network=host \
              -e API_SERVER_PORT=3033 \
              -e CBS_SERVER_ADDRESS=http://localhost:4001 \
              -d adharaprojects/cbs-proxy:temp-ci-test

      - run:
          name: Test cyclos network
          command: |
            # TODO: use some kind of netcat check to test if Cyclos is ready (it is VERY VERY slow to setup!)
            sleep 20
            docker exec cbs-proxy npm test -e API_SERVER_PORT=3033 -e CBS_SERVER_ADDRESS=http://localhost:4001

      - run:
          name: Cleanup remote docker
          command: |
            docker stop cyclos cyclos-db cbs-proxy
            docker rm cyclos cyclos-db cbs-proxy
            docker network rm cyclos-cbs-proxy-test
            # docker stop cyclos cyclos-db cbs-proxy; docker rm cyclos cyclos-db cbs-proxy; docker network rm cyclos-cbs-proxy-test
